"""
Business-specific constants and data for the Halton Cost Sheet Generator.
"""

# Sales contacts with phone numbers
SALES_CONTACTS = {
    'Marc Byford': '(07974 403322)',
    'Karl Nicholson': '(07791 397866)',
    'Dan Butler': '(07703 729686)',
    'Chris Mannus': '(07870 263280)',
    'Dean Griffiths': '(07814 784352)',
    'Kent Phillips': '(07949 016501)'
}

# Estimators with their roles
ESTIMATORS = {
    'Simon Still': 'Lead Estimator',
    'Nick Soton': 'Estimator',
    'Chris Davis': 'Estimator'
}

# Valid canopy models
VALID_CANOPY_MODELS = [
    'KVF', 'UVF', 'CMWF', 'CMWI', 'KVI', 'UVI', 'CXW', 'KVS', 'UVS', 'KSW'
]

# Delivery locations with distances
DELIVERY_LOCATIONS = [
    "Select...",
    "ABERDEEN 590",
    "ABINGDON 110",
    "ALDEBURGH 112",
    "ALDERSHOT 110",
    "ALNWICK 342",
    "ANDOVER 110",
    "ASHFORD 25",
    "AYLESBURY 86",
    "BANBURY 102",
    "BANGOR 324",
    "BARKING 32",
    "BARNET 55",
    "BARNSLEY 209",
    "BARNSTABLE 227",
    "BARROW-IN-FURNESS 348",
    "BASILDON 38",
    "BASINGSTOKE 82",
    "BATH 154",
    "BEDFORD 103",
    "BERWICK-UPON-TWEED 371",
    "BILLERICAY 37",
    "BIRKENHEAD 277",
    "BIRMINGHAM 168",
    "BLACKBURN 283",
    "BLACKPOOL 289",
    "BLANDFORD FORUM 144",
    "BODMIN 273",
    "BOGNOR REGIS 88",
    "BOLTON 259",
    "BOOTLE 272",
    "BOURNEMOUTH 140",
    "BRADFORD 234",
    "BRAINTREE 60",
    "BRIDGEND 205",
    "BRIDLINGTON 244",
    "BRIGHTON 68",
    "BRISTOL 157",
    "BUCKINGHAMSHIRE 109",
    "BURNLEY 296",
    "BURTON UPON TRENT 175",
    "BURY ST EDMUNDS 98",
    "CAMBRIDGE 85",
    "CANNOCK 175",
    "CANTERBURY 30",
    "CARDIFF 192",
    "CARLISLE 356",
    "CARMARTHEN 252",
    "CHELTENHAM 148",
    "CHESTER 268",
    "COVENTRY 146",
    "CHIPPENHAM 136",
    "COLCHESTER 78",
    "CORBY 128",
    "DARTMOUTH 245",
    "DERBY 178",
    "DONCASTER 203",
    "DORCHESTER 160",
    "DORKING 46",
    "DOVER 45",
    "DURHAM 299",
    "EASTBOURNE 57",
    "EASTLEIGH 109",
    "EDINBURGH 428",
    "ENFIELD 49",
    "EXETER 205",
    "EXMOUTH 207",
    "FELIXSTOWE 103",
    "GATWICK 44",
    "GLASGOW 456",
    "GLASTONBURY 164",
    "GLOUCESTER 151",
    "GRANTHAM 143",
    "GREAT YARMOUTH 147",
    "GRIMSBY 215",
    "GUILDFORD 59",
    "HARLOW 47",
    "HARROGATE 236",
    "HARTLEPOOL 286",
    "HASTINGS 40",
    "HEXHAM 325",
    "HEREFORD 184",
    "HIGH WYCOMBE 80",
    "HIGHBRIDGE 187",
    "HONITON 190",
    "HORSHAM 55",
    "HOUNSLOW 55",
    "HUDDERSFIELD 239",
    "HULL 247",
    "HUNTINGDON 94",
    "INVERNESS 619",
    "IPSWICH 94",
    "IRELAND",
    "KENDAL 321",
    "KETTERING 127",
    "KIDDERMINSTER 179",
    "KILMARNOCK 449",
    "KINGSTON UPON HULL 220",
    "KINGSTON UPON THAMES 52",
    "LANCASTER 290",
    "LAUNCESTON 251",
    "LEAMINGTON SPA 146",
    "LEEDS 231",
    "LEICESTER 151",
    "LEIGH ON SEA 45",
    "LEWISHAM 29",
    "LINCOLN 179",
    "LIVERPOOL 258",
    "LLANDUDNO 309",
    "LONDON in FORS GOLD(varies)",
    "LUTON 80",
    "MABLETHORPE 182",
    "MACCLESFIELD 244",
    "MANCHESTER 251",
    "MARGATE 46",
    "MIDDLESBROUGH 286",
    "MILFORD HAVEN 289",
    "MILTON KEYNES 101",
    "MORPETH 327",
    "NANTWICH 232",
    "NEWBURY 101",
    "NEWCASTLE 308",
    "NEWPORT 178",
    "NEWQUAY 178",
    "NORTHAMPTON 116",
    "NORTHUMBERLAND 341",
    "NORWICH 136",
    "NOTTINGHAM 177",
    "OKEHAMPTON 232",
    "OXFORD 106",
    "PENRITH 316",
    "PENZANCE 318",
    "PERTH 477",
    "PETERBOROUGH 124",
    "PETERSFIELD 87",
    "PETWORTH 71",
    "PLYMOUTH 247",
    "PONTEFRACT 221",
    "POOLE 144",
    "PORTSMOUTH 102",
    "READING 88",
    "REIGATE 39",
    "RINGWOOD 130",
    "ROSS-ON-WYE 171",
    "ROTHERHAM 203",
    "SALISBURY 120",
    "SCARBOROUGH 277",
    "SCUNTHORPE 204",
    "SHEFFIELD 205",
    "SHREWSBURY 207",
    "SHROPSHIRE 218",
    "SLOUGH 72",
    "SOUTH SHIELDS 310",
    "SOUTHAMPTON 112",
    "SOUTHEND 52",
    "SOUTHPORT 279",
    "SPALDING 143",
    "ST ALBANS 62",
    "ST IVES 317",
    "STAFFORD 187",
    "STAINES 61",
    "STEVENAGE 72",
    "STIRLING 445",
    "STOCKPORT 257",
    "STOCKTON 278",
    "STOKE-ON-TRENT 205",
    "STRATFORD UPON AVON 151",
    "SUNDERLAND 309",
    "SWINDON 121",
    "TAMWORTH 180",
    "TAUNTON 185",
    "TELFORD 193",
    "TILBURY 34",
    "TORQUAY 227",
    "TUNBRIDGE WELLS 26",
    "UXBRIDGE 74",
    "WAKEFIELD 214",
    "WARMISTER 137",
    "WARWICK 148",
    "WATFORD 67",
    "WELSHPOOL 238",
    "WEMBLEY 55",
    "WEYMOUTH 173",
    "WHITBY 282",
    "WIGAN 252",
    "WINCANTON 149",
    "WINCHESTER 100",
    "WOKING 60",
    "WOLVERHAMPTON 175",
    "WORCESTER 160",
    "WREXHAM 250",
    "YEOVIL 163",
    "YORK 243"
]

# Company addresses dictionary
COMPANY_ADDRESSES = {
    "Airedale Group (Bradford)": "Victoria Road\nPedeshill\nBradford BD23 2BN",
    "Airedale Group (Lutterworth)": "1 St Johns Business Park\nRugby Road\nLutterworth LE17 4HB",
    "Court Catering Equipment Ltd": "Unit 1, Acton Vale Ind. Park,\nCowley Road\nLondon W3 7XA",
    "Humble Arnold Associates": "Farriers House\nFarriers Close\nCodicote\nHertfordshire\nSG4 8DU",
    "Berkeley Projects UK Ltd": "17 Ewell Road\nCheam\nSurrey\nSM3 8DD",
    "Chapman Ventilation Ltd": "15-20 Woodfield Rd\nWelwyn Garden City\nHerts AL7 1JQ",
    "SG Group": "Aspen Way\nPaignton\nDevon TQ4 7QR",
    "ABM Catering for Leisure Ltd": "Algate House\nClydesmuir Rd Ind Est\nCardiff CF24 2QS",
    "C&C Catering Equipment Ltd": "1 Smithy Farm\nChapel Lane\nSaighton\nChester CH3 6EW",
    "Hallmark Kitchens Ltd": "South Barn\nCrockham Farm\nEdenbridge\nKent\nTN8 6SR",
    "Cabiola Foodservice Equipment": "The Bake House\nNarborough Wood Park\nDesford Road\nEnderby\nLeicester LE19 4XT",
    "Ceba Catering Services": "Unit 27, Eastville Close\nEastern Avenue Trading Estate\nGloucester\nGL4 3SJ",
    "Design Installation Service Ltd": "4 Gainsborough House\n42 / 44 Bath Road\nCheltenham\nGL53 7HJ",
    "Nelson Bespoke Commercial Kitchens": "Unit 1\nRowley Industrial Park\nRoslin Road\nActon\nLondon W3 8BH",
    "Airflow Cooling Ltd": "132 Rutland Road\nSheffield S3 9PP",
    "Spectrum Contracts Ltd.": "Unit 11 Dorcan Business Village\nMurdoch Road\nDorcan\nSwindon\nSN3 5HY",
    "CCE Group Ltd": "Unit 1 Bentley Farm\nOld Church Hill\nChingon Hills\nBasildon SS16 6HZ",
    "Shine Food Machinery Ltd": "New Quay Road\nStephenson Street Ind. Est.\nNewport NP19 4FL",
    "HCE Foodservice Equipment Ltd": "School Lane\nChandlers Ford\nEastleigh\nHants SO53 4DG",
    "Vision Commercial Kitchens Limited": "Unit A1, Axis Point,\nHill Top Road,\nHeywood\nLancs OL10 2RQ",
    "Fast Food Systems Ltd.": "Unit 1\nHeadley Park 9\nHeadley Road East\nWoodley\nReading\nBerkshire RG5 4SQ",
    "C. Caswell (Eng) Services Ltd": "Knowsley Road Ind. Est.\nHaslingden\nRossendale\nLancs BB4 4RX",
    "VSS Ltd": "Building 2 ThermoAir Site\nAthy Road\nCarlow\nIreland R93 K635",
    "Reco-Air": "Newmarket 24, Centrix,\nKeys Business Village\nCannock\nStaffordshire\nWS12 2HA",
    "Gratte Brothers Ltd.": "3 Crompton Road\nStevenage\nHertfordshire\nSG1 2XP",
    "HCE Foodservice Equipment Ltd": "School Lane\nChandlers Ford Id Est.\nEastleigh\nHants SO53 4DG",
    "Salix Stainless Steel Production House": "Chester Hall Lane\nBasildon\nEssex SS14 3BG",
    "Stangard Design Solutions Ltd.": "The Dairy\nWolvey Lodge Business Centre\nWolvey\nWarwickshire\nLE10 3HB",
    "AFR Air Conditioning Ltd": "14 Kingsdown Road\nSwindon\nWiltshire\nSN25 6PB",
    "Sigma Catering Equipment": "Unit 4\nPotter Street\nWallsend\nNE28 6LS",
    "CHR Equipment Ltd.": "Astar House\nFourries Bridge\nPreston\nPR5 6GS",
    "MITIE Engineering Services (Retail) Ltd.": "The Millennium Centre\nM4 Crosby Way\nFarnham\nSurrey GU9 7XX",
    "Catering Design Services": "4 Waterside Commerce Park\nTrafford Park\nManchester\nM17 1WD",
    "Salix Stainless Steel Applications": "Production House\nChester Hall Lane\nBasildon\nEssex SS14 3BG",
    "Galgorm Group": "Galgorm Industrial Estate\n7 Corbally Road\nBallymena BT42 1JQ",
    "Michael J Lonsdale": "Unit 1Langley Quay\nWaterside Drive\nLangley\nSlough\nBerkshire\nSL3 6EY",
    "Advance Catering Equipment": "Dantem House\nBlackburn Road\nHoughton Regis\nDunstable\nLU5 5BQ",
    "MITIE Engineering Services (South West) Ltd": "5 Hanover Court\nMatford Close\nMatford Business Park\nExeter\nEX2 8QJ",
    "A C V R Services Ltd": "Unit 4\nNewtown Grange Farm Bu siness Park Orchard\nLeicester\nLE8 8FL",
    "Lockhart Catering Equipment": "6 The Astra Centre\nEdinburgh Way\nHarlow\nEssex\nCM20 2BN",
    "Insitu Fabrications": "Unit19\nButterfield Ind. Est.\nNewtongrange\nBonnyrigg EH19 3JQ",
    "Stephens Catering Equipment": "205 Carnabanaugh Road\nDoughandshane\nBallymena\nCo. Antrim BT42 4NY",
    "Into Design Ltd": "16 Richards Rise\nOxted\nSurrey\nRH8 0TS",
    "Merrick Contracts Ltd": "Bird Point Mill\nKing Henry's Drive\nNew Addington\nSurrey\nCR0 0AE",
    "CKE Service Ltd": "13 High Street\nThames Ditton\nSurrey\nKT7 0SN",
    "Dentons Catering Equipment": "2/4 Clapham High Street\nLondon\nSW4 7UT",
    "Ferro Design Ltd": "Blay's House\nChurchfield Road\nChalfont St Peter\nBucks\nSL9 9EW",
    "Four Seasons Air Conditioning Suppliers Ltd": "Stadium Works\nSedgley Street\nWolverhampton\nWest Midlands\nWV2 3AJ",
    "Stephens Catering Equipment": "Block F, Unit 9\nMaynooth Business Campus\nMaynooth, Co. Kildare.",
    "Reco-Air": "14 Heritage Park\nHayes Way\nCannock\nStaffordshire\nWS11 7LT",
    "Pan-Euro Environmental": "Unit 2, Group House\nAlbon Way\nReigate\nRH2 7JY",
    "Caswell Engineering": "Knowsley Road Ind. Est.\nHaslingden\nRossendale\nLancs BB4 4RR",
    "C A Sothers Ltd": "156 Hockey Hill\nBirmingham\nB18 5AN",
    "RDA": "5 Apollo Court\nMonkton Business Park South\nTyne & Wear NE31 2ES",
    "KCCJ Ltd.": "The Old Granary\nCourt Lodge Farm\nLambden Hill\nDA2 7QY",
    "Contract Catering Equipment": "Unit1, Bentley Farm,\nOld Church Hill, Chingon Hills,\nEssex SS16 6HZ",
    "Fellerman Partnership Ltd": "74 Kimberley Road\nPortsmouth PO4 9NS",
    "Tricon Foodservice Consultants": "St James House\n27-43 Eastern Road\nRomford",
    "Technical Services Ref & A/C Ltd": "Arlingston House\n32 Boundary Road\nNewbury",
    "Sefton Horn Winch": "The Stables\nHome Farm Business Units\nRiverside\nEynsford",
    "Carford Group": "1-4 Mitchell Road\nFernside Park\nFerndown Industrial Estate\nFerndown\nDorset BH21 7SG",
    "Gratte Bros. Catering Equipment Ltd": "3 Crompton Road\nStevenage\nHerts SG1 2XP",
    "Scobie & McIntosh": "15 Brewster Square\nBrucefield Industry Park\nLivingston\nWest Lothian\nEH54 9BJ",
    "SVS Ltd": "Unit 3\nGreencroft Ind. Est.\nAnnfield Plain\nStanley\nCo Durham\nDH9 7YB",
    "Kitchequip": "Canal View\nWaterside Business Park\nNew Lane\nBurscough L40 8JX",
    "Space Catering": "Barnwood Point\nCorinium Avenue\nGlos GL4 3HX",
    "GS Catering Equipment Ltd": "Aspen Way\nPaignton\nDevon TQ4 7QR",
    "GastroNorth Ltd": "Merlin House\nTeam Valley Trading Est\nPrinces Park\nGateshead\nNE11 0NF",
    "Promart Manufacturing Ltd": "2B Caddick Road\nKnowsley Business Park\nPrescot\nMerseyside L34 9HP",
    "Bob Sackett Commercial Catering Projects Ltd": "9 Chesterford Court\nLondon Road\nGreat Chesterford\nEssex CB10 1PF",
    "Vision Commercial Kitchens Limited": "Unit A1, Axis Point,\nHill Top Road,\nHeywood\nLancs OL10 2RQ",
    "Court Catering Equipment Ltd": "8 Cowley Road\nLondon W3 7XA",
    "Main Contract Services Ltd": "Alexandra House\nStation Road\nGrangemouth FK3 8DG",
    "CDS-Wilman": "4 Waterside Commerce Park\nTrafford Park\nManchester M17 1W",
    "AFR Air Conditioning": "14 Kingsdown Road\nSwindon\nWilts SN25 6PB",
    "Western Blueprint Ltd": "Unit B2, 1st Floor\nTrym House Business Centre\nForest Road\nKingswood\nBristol BS15 8DH",
    "Edge Design": "Unit 3 Wiston House\nWiston Avenue\nWorthing\nWest Sussex BN14 7QL",
    "Chapman Ventilation": "15 - 20 Woodfield Road\nWelwyn Garden City\nHertfordshire\nAL7 1JQ",
    "Michael J Lonsdale": "Unit 1 Langley Quay\nWaterside Drive\nBerkshire SL3 6EY",
    "RecoAir": "14 Heritage Park\nHayes Way\nCannock\nStaffordshire WS11 7LT",
    "Humble Arnold": "Farriers House,\nFarriers Close,\nCodicote\nHerts SG4 8DU",
} 